### ISSUE TITLE
Text render bug

### ISSUE THREAD

**Issue by Robindiddams** [chrissbendel/dubtrackmobile#34]
I know what your doing is a work in progress but every other runtime I get this bug and I think its comping from the roomView.js on line 92 and 93:
` <Text style={{fontWeight: 'bold'}}>{message.user.username}</Text>
<Text>{message.message}</Text>`
 guess that messages object might not be loaded yet. Bug disappears when I comment the lines out.

**Comment by chrissbendel** [comment]
ill look into this if its still an issue @Robindiddams , let me know

**Comment by Robindiddams** [comment]
I haven't run into it since nuking and rebuilding the login
